name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - master
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          preCommands: |
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly
            source $HOME/.cargo/env
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
